# Generated by Django 5.1.4 on 2025-04-18 13:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=15)),
                ('rating', models.IntegerField()),
                ('holds', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Climbing_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_logged', models.DateTimeField(default=django.utils.timezone.now)),
                ('climb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.climb')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('logged_climbs', models.ManyToManyField(blank=True, related_name='profile_logged', through='backend.Climbing_Log', to='backend.climb')),
                ('saved_climbs', models.ManyToManyField(blank=True, related_name='profile_saved', to='backend.climb')),
                ('saved_gyms', models.ManyToManyField(blank=True, to='backend.gym')),
            ],
        ),
        migrations.AddField(
            model_name='climbing_log',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.profile'),
        ),
        migrations.AddField(
            model_name='climb',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climbs', to='backend.profile'),
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('angle', models.FloatField()),
                ('size', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='walls/')),
                ('boxes', models.JSONField(blank=True, default=list)),
                ('confidences', models.JSONField(blank=True, default=list)),
                ('classes', models.JSONField(blank=True, default=list)),
                ('masks', models.JSONField(blank=True, null=True)),
                ('gym_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gym')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_walls',
            field=models.ManyToManyField(blank=True, to='backend.wall'),
        ),
        migrations.AddField(
            model_name='climb',
            name='wall_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.wall'),
        ),
    ]
