# Generated by Django 5.1.4 on 2024-12-17 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('angle', models.FloatField()),
                ('size', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='walls/')),
                ('boxes', models.JSONField()),
                ('confidences', models.JSONField()),
                ('classes', models.JSONField()),
                ('masks', models.JSONField(null=True)),
                ('gym_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Climb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=15)),
                ('rating', models.IntegerField()),
                ('holds', models.JSONField()),
                ('wall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.wall')),
            ],
        ),
    ]
